name = "Test website"
description = "Test"
license = "MIT"
tags = ["map"]
min_version = 0.20

[author]
    name = "Hello"
    homepage = "https://philam.github.io/herring-cove/"

# If Porting existing theme
[original]
    author =  "arnp"
    repo = "http://www.github.com/arnp/herring-cove"
